### PR TITLE
finished sass refactor

### PR DESCRIPTION
**Pull request by thesakshi**
Front Page:
a. Changed Waste to Landfill
b. Changed Recyclable to Recycling

General:
a. Changed color scheme
b. Extracted the inline CSS to SASS

### CODE REVIEW

**Comment by jessechong** [comment]
@jjchung3 Hey Joseph, I know you are working on other things, but do you have time to pick this up? Thanks let me know if you can't

**Comment by jjchung3** [comment]
> @jjchung3 Hey Joseph, I know you are working on other things, but do you have time to pick this up? Thanks let me know if you can't

I gotcha.

**Comment by jessechong** [comment]
Thanks Joseph, thanks Sakshi. Sorry for the delay. This is really strange. 

This branch is 4 commits above master but it is lacking certain features that were added into master.

This is the branch
image

This is master
image

**Comment by jessechong** [comment]
Found the issue. 
These two changes weren't being seen for some reason - https://github.com/zotbins/ZotBins-Management-Client/commit/8d9dd8e1c78c3e7c42669649c82573e876113265
https://github.com/zotbins/ZotBins-Management-Client/commit/7863dc5592f8fc8fbe92469bcd25d7fcd7b6b5ea

The two files in particular are "client/src/components/DataVisualization/ChartTabs/index.js" from commit "8d9dd8e" and "client/src/components/Pages/DashboardPage/index.js" from commit "7863dc".

I just merged this branch except for two files and it looks good. Thanks for all the hardwork everybody!

**Pull request closed without merging**
